export { defualt as Article } from './article/Article'
export { defualt as Brand } from './brand/Brand'
export { defualt as CTA } from './cTA/CTA'
export { defualt as Feature } from './feature/Feature'
export { defualt as Navbar } from './navbar/Navbar'
